#!/usr/bin/env python3
import logging
from src.getstats import EWBFStats
from src import init

if __name__ == '__main__':
    try:
        init.initialize_logger()
        logging.info('Starting EWBF-statsd...')
        stats = EWBFStats()
        stats.poll_stats()
    except Exception as e:
        logging.critical('Unhandled exception:', exc_info=True)
        raise